---

pf3server_url: local.pf3server.com
pf3server_runmode: profile
pf3server_docroot: /var/www/pf3server
pf3server_ssl: /home/vagrant/credentials

pf3server_deploy_host: local.pf3server.com
pf3server_deploy_user: vagrant

php_pm_max_children: 2
php_pm_start_servers: 1
php_pm_min_spare_servers: 1
php_pm_max_spare_servers: 2

php_fpm_user: vagrant
php_fpm_group: vagrant
php_memory_limit: 16M
php_upload_max_filesize: 2M
php_post_max_size: 8M
php_cgi_fix_pathinfo: 0
php_realpath_cache_size: 96k
php_opcache_enable: 1
php_opcache_memory_consumption: 64
php_opcache_interned_strings_buffer: 16
php_opcache_max_accelerated_files: 16228
php_opcache_validate_timestamps: 1
